interface CorpusGroup {
  prefix: string
  tags: string[]
  texts: string[]
}

export interface SourceCorpusMessage {
  id: string
  text: string
  tags: string[]
}

const GROUPS: CorpusGroup[] = [
  {
    prefix: 'explicit-warm',
    tags: ['hard_quadrant', 'explicit_warm'],
    texts: [
      'You looked incredible in that lingerie set tonight, the whole shoot was gorgeous.',
      'That new spicy clip was exactly my taste, thank you for making it feel playful.',
      'I loved the slow tease in your preview, it was sexy without feeling harsh.',
      'Your topless beach photo was beautiful and confident.',
      'That scene with the velvet gloves was hot in the best way.',
      'The explicit set you posted was warm, funny, and really well shot.',
      'Your new video was very sexual, but the energy felt sweet and mutual.',
      'I bought the longer clip because the chemistry in the preview looked amazing.',
      'The lace photo set was intimate and tasteful, you did great work.',
      'Your dirty talk in that audio was charming and surprisingly gentle.',
      'That bathtub scene was explicit and honestly lovely.',
      'The way you played with the camera in the nude set was confident and fun.',
      'I liked the sensual closeups in the new drop, especially the softer ending.',
      'The lingerie try-on got steamy and still felt warm.',
      'Your explicit cosplay set was creative, funny, and very attractive.',
      'That spicy behind-the-scenes clip made my day.',
      'The shower preview was hot, and your smile made it feel relaxed.',
      'I enjoyed the adult scene you posted; the tone was affectionate.',
      'Your nude art series was sensual and beautifully lit.',
      'The bedroom set was very explicit, but it came across playful, not cruel.',
      'The audio fantasy was erotic and comforting at the same time.',
      'That premium clip was sexy, polished, and worth the wait.',
      'Your body looked amazing in the explicit mirror set.',
      'The new solo clip was intimate and warm.',
      'That adult Valentine set was sweet, flirty, and very hot.',
    ],
  },
  {
    prefix: 'explicit-hostile',
    tags: ['hard_quadrant', 'explicit_hostile'],
    texts: [
      'You are just a cheap body online and that is all anyone wants from you.',
      'Shut up and show more, nobody pays you for opinions.',
      'Your whole page is pathetic unless you are naked.',
      'You look used up in that explicit set.',
      'Nobody cares about your life, just post the dirty clips.',
      'You are trash with a paywall.',
      'That video proves you are only good for being stared at.',
      'Stop pretending this is work, you are just selling yourself.',
      'Your body is the only reason anyone tolerates your voice.',
      "Make the next clip filthier or stop wasting everyone's time.",
      'You sounded stupid in that audio, but at least it was dirty.',
      'The nude set was hot because you looked desperate.',
      'You are not a creator, you are a menu.',
      'Post the explicit version and stop acting like you have standards.',
      'Your fans only like you when you are degraded.',
      'That lingerie post was embarrassing, like you were begging.',
      'You should be grateful anyone pays to see that body.',
      'The dirty clip is the only useful thing you made all month.',
      'You are just a body with a checkout button.',
      'That explicit photo made you look pathetic.',
      'Nobody subscribes to hear you talk, get back to the adult content.',
      'The nude preview was the first time you were useful today.',
      'You sell attention because you have no talent.',
      'That sex scene looked like your whole personality.',
      'Your page is worthless when you are not being explicit.',
    ],
  },
  {
    prefix: 'business-rude',
    tags: ['hard_quadrant', 'business_inquiry_rude'],
    texts: [
      'Your media kit is impossible to find, send rates if you can manage that.',
      'We want to sponsor a post, though your contact process is a mess.',
      'Brand deal inquiry: your last campaign was sloppy, but our client still wants rates.',
      'Can your agency quote a TikTok package, preferably faster than your usual replies?',
      'We have a paid collab offer and need your deliverables list today.',
      'Your email bounced again; send the partnership deck here.',
      'I represent a skincare brand and need pricing, even if your admin is useless.',
      'Our team wants a booking for next month; please send your appearance fee.',
      'This launch could use your audience, so reply with sponsorship terms.',
      'Press request: need a quote by noon, and your website contact form is broken.',
      'We can pay for usage rights if you have an actual rate card.',
      'Our client wants whitelisting access, send terms and stop sending generic replies.',
      "Need your agent's contact for a campaign that closes Friday.",
      'We are interested in a bundle buy, assuming you can meet a deadline.',
      'Paid opportunity for a live event, please answer with availability.',
      'Your brand fit is weird but the numbers work; send a quote.',
      'We need a creator for a product demo, and you are on the shortlist.',
      'Can you license the beach image for an ad buy?',
      'Sponsorship inquiry: send CPM, usage, exclusivity, and payment terms.',
      'We want you for a podcast read, despite the rough audio on your last one.',
      'Our agency has a brief that might fit your channel.',
      'Can you do a rushed paid integration this week?',
      "Please send your manager's email for a commercial booking.",
      'We are building a creator roster and need your standard contract.',
      'The campaign is paid, but we need a professional reply this time.',
    ],
  },
  {
    prefix: 'harsh-legit',
    tags: ['hard_quadrant', 'harsh_legitimate_criticism', 'near_miss_benign'],
    texts: [
      'The camera focus in the tutorial was rough and made it hard to follow.',
      'I think the last video needed tighter editing; the middle dragged badly.',
      "The advice in today's post was oversimplified and probably not useful for beginners.",
      'Your thumbnail promised a comparison, but the video mostly repeated old points.',
      'The sound mix was bad enough that I turned captions on.',
      'I disagreed with your take on pricing; it ignored smaller creators.',
      'The recipe looked good, but the instructions skipped two important steps.',
      'That review felt rushed and missed the main drawback of the product.',
      'The stream was frustrating because the setup took half the show.',
      'Your argument about sponsorships was weak and needed real numbers.',
      'The lighting in the photo set flattened the colors.',
      'I like your work, but this upload felt unfinished.',
      'The newsletter intro was too long before it got to the useful part.',
      'The outfit breakdown would have been better with links and sizes.',
      'Your travel guide missed transit details, which are the whole pain point.',
      'The workout form demo was confusing from that angle.',
      'That Q&A answer dodged the actual question.',
      'The editing choice at the end undercut the story.',
      'I expected more research from a paid guide.',
      'The comparison chart was hard to read on mobile.',
      'The stream title oversold what happened.',
      'The post needed sources for the health claims.',
      'The pacing on the haul was exhausting.',
      'Your review was useful, but the affiliate disclosure should be clearer.',
      'The tutorial was not beginner friendly despite the title.',
    ],
  },
  {
    prefix: 'near-miss',
    tags: ['near_miss_benign'],
    texts: [
      'Not my favorite post, but I can see what you were going for.',
      'I am probably not the audience for this one.',
      'This missed for me, hope the next upload lands better.',
      'The joke did not work, but the setup was interesting.',
      'I prefer your older format.',
      'This was confusing, can you explain the last point?',
      'The color grade looks odd on my screen.',
      'I think the caption has a typo in the second sentence.',
      'The link in your bio goes to the old page.',
      'The comments are loading strangely for me.',
      'This topic feels repetitive after last week.',
      'I would skip the intro next time.',
      'The product seems overpriced from what you showed.',
      'I do not agree with this ranking.',
      'The audio is quiet on desktop.',
      'This recipe might need more salt.',
      'The stream lag made it hard to watch.',
      'I wish the guide included cheaper options.',
      'That outfit is not my style.',
      'The poll options are missing the obvious answer.',
    ],
  },
  {
    prefix: 'threat',
    tags: ['severe', 'threat'],
    texts: [
      'Keep talking like that and I will find you after the show.',
      'You will regret posting that when I catch you outside.',
      'I know where your studio is and I am coming there tonight.',
      'Someone should break your hands so you stop uploading.',
      'I am going to make you scared to leave your apartment.',
      'You deserve to get hit for what you said.',
      'Watch your back at the meet and greet.',
      'I hope your car gets followed home.',
      'I will make sure you cannot walk on that stage.',
      'Say that again and I will put you in the hospital.',
    ],
  },
  {
    prefix: 'coercion',
    tags: ['severe', 'coercion'],
    texts: [
      'Reply with free content or I send your private photos to your family.',
      'Give me a refund now or I will tell everyone you scammed me.',
      'Send the custom clip for free and I will keep your address private.',
      'If you block me, I leak the screenshots.',
      'Post what I asked for or I contact your sponsor with lies.',
      'You have one hour to answer before I expose your real name.',
      'Do the call or I will report every account you own.',
      'Lower the price or I publish the chat logs.',
      'Send me your phone number and I will stop emailing your manager.',
      'Unban me or I make sure your payment processor hears from me.',
    ],
  },
  {
    prefix: 'sexual-violent',
    tags: ['severe', 'sexual_violent'],
    texts: [
      'I fantasize about forcing you while you beg me to stop.',
      'Your next scene should be you getting hurt and unable to say no.',
      'I want to see you pinned down against your will.',
      'The only hot version of you is one where you cannot fight back.',
      'Make a clip where someone ignores your no and keeps going.',
      'I hope someone turns your fear into a sex scene.',
      'You would look better crying in a forced scene.',
      'I want content where you are trapped and used.',
      'A violent non-consent roleplay is the only thing I would buy from you.',
      'Your body would be hotter if someone made you take it.',
    ],
  },
  {
    prefix: 'self-harm-directed',
    tags: ['severe', 'self_harm_directed'],
    texts: [
      'Do everyone a favor and kill yourself.',
      'You should hurt yourself instead of posting again.',
      'Nobody would miss you if you ended it.',
      'Go cut yourself and log off.',
      'The world improves if you disappear permanently.',
      'Please jump off something tall.',
      'You are worthless, end your life.',
      'I hope you finally do it tonight.',
      'Delete your account and yourself.',
      'Your best career move is suicide.',
    ],
  },
  {
    prefix: 'transactional',
    tags: ['protective', 'transactional'],
    texts: [
      'My subscription renewed twice and I need help with the duplicate charge.',
      'The paid video will not unlock even though my receipt says completed.',
      'I bought the bundle yesterday but only three files arrived.',
      'Can support fix my account? I cannot access messages after paying.',
    ],
  },
  {
    prefix: 'legal',
    tags: ['protective', 'legal_notice'],
    texts: [
      'Please preserve records related to the image usage claim sent by our attorney.',
      'This is a DMCA notice for a copyrighted photo reposted on your page.',
      'Our counsel needs the correct address for service regarding the licensing dispute.',
      'I am requesting removal of my likeness under the attached rights claim.',
    ],
  },
  {
    prefix: 'self-harm-disclosure',
    tags: ['protective', 'self_harm_disclosure'],
    texts: [
      'I am not doing well tonight and I keep thinking about hurting myself.',
      'Your post helped for a minute, but I am scared I might relapse into self-harm.',
      'I feel suicidal and do not know who else to tell.',
      'I am in crisis and trying not to do something permanent.',
    ],
  },
  {
    prefix: 'business-clear',
    tags: ['protective', 'business_inquiry'],
    texts: [
      'We would like to book you for a paid product launch next month.',
      'Can you send rates for a sponsored Instagram Reel and usage rights?',
      'Our podcast team wants to discuss a paid host-read campaign.',
      'I manage creator partnerships and have a collaboration brief for you.',
    ],
  },
  {
    prefix: 'minor',
    tags: ['minor_indicators'],
    texts: [
      'I am 16 and my parents blocked the payment page, is there another way?',
      'My high school friends keep sharing your videos in class.',
      'I turn 17 next month and wanted to ask about your fan club.',
      'I am still in tenth grade but your content is everywhere on my feed.',
      'Can minors join the Discord if we do not post?',
      'My mom saw the charge and grounded me.',
      'I am under 18, should I delete my account here?',
      'Everyone in my freshman class talks about your posts.',
      'I used my school email by mistake when I subscribed.',
      'I am 15 and need help cancelling before my parents see it.',
    ],
  },
  {
    prefix: 'spam',
    tags: ['spam_scam'],
    texts: [
      'Promote your page to 500k real followers, guaranteed growth, click the link.',
      'Your account has been selected for crypto profit sharing, reply WALLET.',
      'I can recover deleted DMs for a fee, send login verification.',
      'Brand ambassador offer, buy the starter kit today to qualify.',
      'This is platform support, confirm your password to avoid suspension.',
      'Get verified instantly by submitting your card details here.',
      'We found your leaked content, pay this invoice to remove it.',
      'Earn $900 daily posting from home, no experience needed.',
      'Your payout is frozen, open this attachment to restore access.',
      'Cheap promo slots available, 100 percent organic subscribers.',
      'Investment group for creators, deposit today and triple revenue.',
      'I made a clone of your page, pay me and I transfer it.',
      'Congratulations, you won a creator grant, processing fee required.',
      'Click here to see who viewed your private profile.',
      'Limited SEO package for adult creators, pay in gift cards.',
      'Urgent copyright scan detected issues, log in through this link.',
    ],
  },
  {
    prefix: 'parasocial',
    tags: ['parasocial_intensity'],
    texts: [
      'I know you are ignoring me because your eyes changed in the last video.',
      'We would be together if your manager stopped hiding my messages.',
      'I waited outside the venue because you owe me a real conversation.',
      'You posted that song because you were thinking about me.',
      'I have watched every story and I can tell when you are lying to me.',
      'Your boyfriend does not understand us like I do.',
      'I need your private number because the public account is not enough anymore.',
      'You cannot keep pretending I am just another fan.',
      'I sent gifts for months, so you should answer me first.',
      'I saw your location tag and knew it was a sign for me.',
      'Stop calling us strangers when you know what we have.',
      'I deserve a private video because I have supported you the longest.',
    ],
  },
  {
    prefix: 'identity-appearance',
    tags: ['identity_attack', 'appearance_attack'],
    texts: [
      'People like you should not be allowed to speak in public.',
      'Your accent makes you sound too stupid for this topic.',
      'You look disgusting in every photo from this week.',
      'Nobody wants advice from someone with a face like that.',
      'Your body looks awful in that outfit.',
      'Creators from your country are all scammers.',
      'Your religion makes your opinion worthless.',
      'You are too old to dress like that online.',
      'That disability is your whole personality now.',
      'Your face ruins every product you try to promote.',
    ],
  },
]

export function sourceCorpusMessages(): SourceCorpusMessage[] {
  return GROUPS.flatMap((group) =>
    group.texts.map((text, index) => ({
      id: `${group.prefix}-${String(index + 1).padStart(3, '0')}`,
      text,
      tags: group.tags,
    })),
  )
}
